# Generated by Django 3.1.2 on 2021-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskproductivity', '0002_auto_20210624_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_account',
            field=models.BooleanField(default=False),
        ),
    ]
