# Generated by Django 3.1.2 on 2021-06-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskproductivity', '0003_user_verified_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recovery',
            new_name='Recoveries',
        ),
        migrations.RenameModel(
            old_name='Verification',
            new_name='Verifications',
        ),
    ]
