# Generated by Django 3.2.3 on 2021-10-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskproductivity', '0008_alter_recoveries_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='erdates',
            name='departure',
            field=models.DateField(null=True),
        ),
    ]
