# Generated by Django 3.2.3 on 2021-10-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskproductivity', '0009_erdates_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='erdates',
            name='reported_date',
            field=models.DateField(null=True),
        ),
    ]
