# Generated by Django 3.2.3 on 2021-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskproductivity', '0010_erdates_reported_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='erdates',
            name='online_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='erdates',
            name='online_start',
            field=models.DateField(null=True),
        ),
    ]
