name: Pre-deploy Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu_test:
    runs-on: ubuntu-latest
    env:
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/task_productivity"
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: task_productivity
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt    
    - name: Run Tests
      run: |
        python manage.py test taskproductivity.tests.testdb
        python manage.py test taskproductivity.tests.test_homepage.HomepageTestCase
        python manage.py test taskproductivity.tests.test_homepage.UITestCaseChrome
        python manage.py test taskproductivity.tests.test_homepage.UITestCaseFireFox
  windows_test:
    runs-on: windows-latest
    env:
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/task_productivity"
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: task_productivity
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt    
    - name: Run Tests
      run: |
        python manage.py test taskproductivity.tests.testdb
        python manage.py test taskproductivity.tests.test_homepage.HomepageTestCase
        python manage.py test taskproductivity.tests.test_homepage.UITestCaseChrome
        python manage.py test taskproductivity.tests.test_homepage.UITestCaseFireFox
        python manage.py test taskproductivity.tests.test_homepage.UITestCaseEdge
